version: '2'
services:

  dbpostgres:
    image: postgres
    volumes_from:
      - dbdata
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Password

  dbmysql:
    image: mysql
    volumes_from:
      - mysqldata
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: "customers"


  dbdata:
    image: alpine
    volumes:
      - /var/lib/postgresql/data

  mysqldata:
    image: alpine
    volumes:
      - /var/lib/mysql
